### ISSUE TITLE
Questions about the result

### ISSUE THREAD

**Issue by Hanksd** [SadeghAliakbarian/Multi-Stage-LSTM-for-Action-Anticipation#3]
I have run all your code, and I find that the accuracy of JHMDB dataset is only 20%~25%, so I want to know that the code has some errors. And i find some:
1.In action_context_train.py ,your decay is 0.005,and in your paper is 0.0005;and I also find that 'featurewise_center=True, featurewise_std_normalization=True,' does not work,because of lacking the code such as 'datagen.fit(x_train)'.
2.action_aware_features.py: I find that 'feature'is a 50*4096 array,but the output shape of 'np.array(action_aware([feat_inp, 0]))[0][0]' is 1024,so the code 'feature[fr] = np.array(action_aware([feat_inp, 0]))[0][0]' does not work.
3. evaluation.py:'x_test_context = item[0], x_test_action = item[1]' should be 'x_test_context[index] = item[0],x_test_action[index] = item[1]'.
Though I find these errors,but I still can not make the acc to 55%,so I want your help.

**Comment by gogo03** [comment]
hi,have you run the author's code? but i found some errors and couldnot run this project. could you give your code to check it? my email is :635196543@qq.com.
thx

**Comment by Hanksd** [comment]
@gogo03 You must read this issue :https://github.com/SadeghAliakbarian/Multi-Stage-LSTM-for-Action-Anticipation/issues/4#issue-324941259, and you will find that this project has a logic errors. Because the CAM features in this paper needs the ground truth class. And I have successfully modified the code by referring to the paper. If you need it, I can send it to you when I get back to school.

**Comment by gogo03** [comment]
thank you very much.if you can share the working codes my email is 635196543@qq.com
thank you again

**Comment by gogo03** [comment]
@Hanksd ,hi,Have you returned to school? What is the accuracy of your test? I want to test your new code. Thank you. I found that the author was not here and did not answer any questions.

**Comment by Hanksd** [comment]
@gogo03 Recently, things are a little bit more. I have uploaded the code to this website（https://github.com/Hanksd/Multi-Stage-LSTM-for-Action-Anticipation-modified-version-）.

**Comment by gogo03** [comment]
got it ,thank you very much.
good job you've done. Do you get the same result as the original author's paper?




------------------ 原始邮件 ------------------
发件人: "Hanksd"<notifications@github.com>;
发送时间: 2018年9月10日(星期一) 晚上11:10
收件人: "SadeghAliakbarian/Multi-Stage-LSTM-for-Action-Anticipation"<Multi-Stage-LSTM-for-Action-Anticipation@noreply.github.com>;
抄送: "gogo"<635196543@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [SadeghAliakbarian/Multi-Stage-LSTM-for-Action-Anticipation]Questions about the result (#3)




@gogo03 Recently, things are a little bit more. I have uploaded the code to this website（https://github.com/Hanksd/Multi-Stage-LSTM-for-Action-Anticipation-modified-version-）.

**Comment by Hanksd** [comment]
Yeah, I had got the same result

**Comment by gogo03** [comment]
good job!@Hanksd

**Comment by gogo03** [comment]
oh,you comment them.I understood.

**Comment by gogo03** [comment]
hi.my output is like this while runnint evaluation.py.
w/ Temporal Average Pooling: 0.3843283582089552 -- wo/ Temporal Average Pooling: 0.10998134615261164
w/ Temporal Average Pooling: 0.3805970149253731 -- wo/ Temporal Average Pooling: 0.1303171681156799
w/ Temporal Average Pooling: 0.3843283582089552 -- wo/ Temporal Average Pooling: 0.14710821011173192
w/ Temporal Average Pooling: 0.3917910447761194 -- wo/ Temporal Average Pooling: 0.16399254171705957
w/ Temporal Average Pooling: 0.41044776119402987 -- wo/ Temporal Average Pooling: 0.17723881664560803
w/ Temporal Average Pooling: 0.417910447761194 -- wo/ Temporal Average Pooling: 0.19160448548509112
w/ Temporal Average Pooling: 0.417910447761194 -- wo/ Temporal Average Pooling: 0.204944033676119
w/ Temporal Average Pooling: 0.4253731343283582 -- wo/ Temporal Average Pooling: 0.2183768738116791
w/ Temporal Average Pooling: 0.43283582089552236 -- wo/ Temporal Average Pooling: 0.23125001098682632
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.24477612705373053
w/ Temporal Average Pooling: 0.44776119402985076 -- wo/ Temporal Average Pooling: 0.258022390639604
w/ Temporal Average Pooling: 0.44402985074626866 -- wo/ Temporal Average Pooling: 0.2685634360384585
w/ Temporal Average Pooling: 0.45149253731343286 -- wo/ Temporal Average Pooling: 0.2807835878720924
w/ Temporal Average Pooling: 0.45149253731343286 -- wo/ Temporal Average Pooling: 0.2928171727194715
w/ Temporal Average Pooling: 0.44776119402985076 -- wo/ Temporal Average Pooling: 0.3045709044186037
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.3138059849169717
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.3199626903480558
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.3277985177822967
w/ Temporal Average Pooling: 0.43656716417910446 -- wo/ Temporal Average Pooling: 0.3350746346943414
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.3401119384303022
w/ Temporal Average Pooling: 0.44402985074626866 -- wo/ Temporal Average Pooling: 0.34580225286199084
w/ Temporal Average Pooling: 0.44402985074626866 -- wo/ Temporal Average Pooling: 0.35027985385994415
w/ Temporal Average Pooling: 0.44402985074626866 -- wo/ Temporal Average Pooling: 0.35708956842991846
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.3638992638730291
w/ Temporal Average Pooling: 0.44029850746268656 -- wo/ Temporal Average Pooling: 0.3693097104777151
w/ Temporal Average Pooling: 0.43283582089552236 -- wo/ Temporal Average Pooling: 0.37425372716206223
w/ Temporal Average Pooling: 0.43283582089552236 -- wo/ Temporal Average Pooling: 0.37798506955602273
w/ Temporal Average Pooling: 0.43656716417910446 -- wo/ Temporal Average Pooling: 0.3832089562914265
w/ Temporal Average Pooling: 0.4253731343283582 -- wo/ Temporal Average Pooling: 0.38703359285397315
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.39039181506455833
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.3939365904722641
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.39748135520451106
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.4010261368395677
w/ Temporal Average Pooling: 0.417910447761194 -- wo/ Temporal Average Pooling: 0.4047574730061773
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.4076492724133961
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.41016793117594363
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.4120335970351945
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.41305971145629883
w/ Temporal Average Pooling: 0.4216417910447761 -- wo/ Temporal Average Pooling: 0.4150186665912173



is correct?thx




------------------ 原始邮件 ------------------
发件人: "Hanksd"<notifications@github.com>;
发送时间: 2018年9月11日(星期二) 上午9:07
收件人: "SadeghAliakbarian/Multi-Stage-LSTM-for-Action-Anticipation"<Multi-Stage-LSTM-for-Action-Anticipation@noreply.github.com>;
抄送: "gogo"<635196543@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [SadeghAliakbarian/Multi-Stage-LSTM-for-Action-Anticipation]Questions about the result (#3)




Yeah, I had got the same result
